spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    host: localhost
    database: 5
dubbo:
  application:
    name: dubbo-apistory-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848/
