spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cd-cdb-s1n7juto.sql.tencentcdb.com:63951/apistory # gxy的MySQL
    username: root
    password: liangquan0302
  redis:
    port: 6379
    host: 124.220.82.79 # gxy 服务器
    database: 7
dubbo:
  application:
    name: dubbo-apistory-admin
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://124.220.82.79:8848/ # gxy 服务器