spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apistory # Gxy 的服务器
    username: root
    password: "030201"
  redis:
    port: 6379
    host: localhost
    database: 6

dubbo:
  application:
    name: dubbo-apistory-admin
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848/ # gxy 服务器