spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cd-cdb-s1n7juto.sql.tencentcdb.com:63951/apistory # Gxy的MySQL
    username: root
    password: liangquan0302
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: 124.220.82.79
    database: 5

dubbo:
  application:
    name: dubbo-apistory-admin
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://124.220.82.79:8848/ # gxy 服务器